---
title: Ronik Design
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
description: Ronik is a digital creative agency. We believe in smart design and progressive
  technologies in all media.
url: https://ronik-design.github.io
author: Ronik Design
destination: "./_site"
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
exclude:
- vendor
- node_modules
- package.json
- rollup.config.js
- postcss.config.js
- Gemfile
- Gemfile.lock
show_drafts: 
limit_posts: 0
future: false
unpublished: false
baseurl: 
show_dir_listing: false
permalink: pretty
paginate_path: "/page:num"
quiet: false
verbose: false
liquid:
  error_mode: lax
repository: ronik-design/ronik-design.github.io
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
compress_html:
  ignore:
    envs:
    - development
  blanklines: false
  profile: false
