# Basics
title: Ronik Design
description: Ronik is a digital creative agency. We believe in smart design and progressive technologies in all media.
url: https://ronik-design.github.io
author: Ronik Design

# Where things are
destination:  ./_site
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Handling Reading
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
keep_files:   []
include:      []
exclude:
  - vendor
  - node_modules
  - package.json
  - rollup.config.js
  - postcss.config.js
  - Gemfile
  - Gemfile.lock

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Serving
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      America/New_York

quiet:    false
verbose:  false

liquid:
  error_mode: lax

# Required for github-metadata
repository: ronik-design/ronik-design.github.io

# Plugins - these are all the plugins currently supported in the GitHub Pages environment
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
whitelist:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false

# Html Compressor
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: 
      - development
  blanklines: false
  profile: false
  startings: []

# Collections
collections:
  posts:
    output:   true

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
